### ISSUE TITLE
Cannot read properties of undefined (reading 'usernameAttribute')

### ISSUE THREAD

**Issue by kgogolek** [immobiliare/backstage-plugin-ldap-auth#135]
Hi

I hope you may be able to help me. I am trying to set up the plugin to work on our backstage
the config we have is as follows:

```
    auth:
        environment: production
        providers:
            ldap:
                production:
                    ldapAuthentication:
                        userDn: 'ou=Users,o=XXXXXXXXX,dc=host,dc=com'
                        userSearchBase: '(&(memberOf=cn=Team-X,ou=Users,o=XXXXXXXXX,dc=host,dc=com)(uid=%s))'         
                        adminDn: uid=ldap-ser,ou=Users,o=XXXXXXXXX,dc=host,dc=com
                        adminPassword: ${LDAP_SECRET}
                        ldapOpts:
                            url:
                                - "ldaps://ldap.host.com"
                            tlsOptions:
                                rejectUnauthorized: true
```

but every time we enter the credentials we get the following error:

```
{"level":"error","message":"Cannot read properties of undefined (reading 'usernameAttribute')","service":"backstage","stack":"TypeError: Cannot read properties of undefined (reading 'usernameAttribute')\n    at ProviderLdapAuthProvider.defaultLDAPAuthentication [as ldapAuthentication] (/app/node_modules/@immobiliarelabs/backstage-plugin-ldap-auth-backend/dist/index.cjs.js:141:11)\n    at ProviderLdapAuthProvider.refresh (/app/node_modules/@immobiliarelabs/backstage-plugin-ldap-auth-backend/dist/index.cjs.js:200:36)\n    at handleReturn (/app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at bound refresh (/app/node_modules/express-promise-router/lib/express-promise-router.js:64:7)\n    at handleReturn (/app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at bound refresh (/app/node_modules/express-promise-router/lib/express-promise-router.js:64:7)\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)\n    at next (/app/node_modules/express/lib/router/route.js:144:13)\n    at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)","type":"errorHandler"}
```

The code that corresponds to this is line:

```
const { usernameAttribute = "uid" } = ldapAuthOptions;
```
in:

```
async function defaultLDAPAuthentication(username, password, ldapAuthOptions, authFunction = ldapAuthentication.authenticate) {
  const { usernameAttribute = "uid" } = ldapAuthOptions;
  const userDn = ldapEscape.dn`${usernameAttribute}=${username},` + ldapAuthOptions.userSearchBase;
  const authObj = {
    ...ldapAuthOptions,
    username,
    usernameAttribute,
    userDn,
    userPassword: password
  };
  try {
    const user = await authFunction(authObj);
    if (!user[usernameAttribute]) {
      throw new Error(AUTH_USER_NOT_FOUND);
    }
    return { uid: user[usernameAttribute] };
  } catch (e) {
    console.error(
      "There was an error when trying to login with ldap-authentication"
    );
    throw e;
  }
}
```
I am really baffled by why this is happening as the config and the code looks right
