### ISSUE TITLE
LDAP Auth with Free IPA

### ISSUE THREAD

**Issue by Ferdbugs** [immobiliare/backstage-plugin-ldap-auth#142]
Hi, I've been trying to setup this plugin to authorize with a Free IPA server I've setup on my local. 

I've installed both front-end and backend plugins, and am on the latest version of backstage.

But I've been receiving this error whenever I startup backstage and load the auth page: 

![image](https://user-images.githubusercontent.com/33251050/205530784-88ff8956-5005-4f4d-8fc8-a006593242ea.png)

```
{"error":{"name":"TypeError","message":"argument name is invalid","level":"error","service":"backstage","stack":"TypeError: argument name is invalid\n    at Object.serialize (/home/ferdbugs/projects/backstage/backstage-dev/node_modules/express/node_modules/cookie/index.js:120:11)\n    at ServerResponse.res.cookie (/home/ferdbugs/projects/backstage/backstage-dev/node_modules/express/lib/response.js:884:36)\n    at ServerResponse.clearCookie (/home/ferdbugs/projects/backstage/backstage-dev/node_modules/express/lib/response.js:827:15)\n    at ProviderLdapAuthProvider.refresh (/home/ferdbugs/projects/backstage/backstage-dev/node_modules/@immobiliarelabs/backstage-plugin-ldap-auth-backend/dist/index.cjs.js:241:11)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"},"request":{"method":"POST","url":"/api/auth/ldap/refresh"},"response":{"statusCode":500}}

```

app-config:

```
auth:
    # see https://backstage.io/docs/auth/ to learn about auth providers
  environment: development
  providers:
    # github:
    #   development:
    #     clientId: ${GITHUB_CLIENT_ID}
    #     clientSecret: ${GITHUB_CLIENT_SECRET}
    ldap:
      development:
        cookies:
          secure: false # https cookies or not
          field: '' # default to "backstage-token"
        ldapAuthenticationOptions:
          userDn: 'cn=users,cn=accounts,dc=myhome,dc=local' 
          userSearchBase: 'dc=myhome,dc=local'
          usernameAttribute: 'uid'
          adminDn: uid=admin,cn=users,cn=accounts,dc=myhome,dc=local
          adminPassword: ${LDAP_USER_SECRET}
          ldapOpts:
            url:
                - 'ldaps://ipasrv.myhome.local'
            tlsOptions:
                rejectUnauthorized: false
```
auth.ts 

![image](https://user-images.githubusercontent.com/33251050/205531159-0d3fee92-f58d-4afb-b1c9-b43781f531cb.png)

catalog.ts 

![image](https://user-images.githubusercontent.com/33251050/205531192-3ec4cb9b-2e40-48ee-917e-00ce9a945b4c.png)

app.tsx

![image](https://user-images.githubusercontent.com/33251050/205531237-ddb53812-a6b3-48b1-914b-b674b647db32.png)

TIA for any help on this issue!
