### ISSUE TITLE
Auth error 

### ISSUE THREAD

**Issue by kamenskiyyyy** [immobiliare/backstage-plugin-ldap-auth#231]
Hello, 

I’m try to setup auth LDAP with this plugin, but I get this error.

```
{
    "error": {
        "name": "NotFoundError",
        "message": "User not found",
        "stack": "NotFoundError: User not found\n    at CatalogAuthResolverContext.findCatalogUser (/Users/mac/WebstormProjects/pochtatech/backstage/node_modules/@backstage/plugin-auth-backend/dist/index.cjs.js:3255:13)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async ProviderLdapAuthProvider.defaultAuthHandler [as authHandler] (/Users/mac/WebstormProjects/pochtatech/backstage/node_modules/@immobiliarelabs/backstage-plugin-ldap-auth-backend/dist/index.cjs.js:95:29)\n    at async ProviderLdapAuthProvider.refresh (/Users/mac/WebstormProjects/pochtatech/backstage/node_modules/@immobiliarelabs/backstage-plugin-ldap-auth-backend/dist/index.cjs.js:223:27)"
    },
    "request": {
        "method": "POST",
        "url": "/api/auth/ldap/refresh"
    },
    "response": {
        "statusCode": 404
    }
}
```

Config:
```
auth:
  environment: development
  # see https://backstage.io/docs/auth/ to learn about auth providers
  providers:
    ldap:
      development:
        cookies:
          secure: false
          field: 'backstage-token'
        ldapAuthenticationOptions:
          userSearchBase: 'ou=FGUP,dc=main,dc=russianpost,dc=ru'
          usernameAttribute: 'sAMAccountName'
          adminDn: ${AUTH_LDAP_BIND_DN}
          adminPassword: ${AUTH_LDAP_BIND_PASSWORD}
          ldapOpts:
            url:
              - 'ldap://${LDAP_URL}'
            tlsOptions:
              rejectUnauthorized: false
```

The user exists in the LDAP system, but the plugin does not find him
