### ISSUE TITLE
Request failed with status 500 Invalid Credentials

### ISSUE THREAD

**Issue by ahmetuten** [immobiliare/backstage-plugin-ldap-auth#579]
Hi,

I'm trying to implement your LDAP login, but I'm getting InvalidCredentials error despite the credentials are true.

I have implemented Backstage's LDAP plugin and I'm successfully getting my user and groups to my catalog with it. I follow your docs and give exact same configs to your plugin but I get the relevant error.

Here are my configs for your plugin:

```
auth:
  environment: development
  providers:
    ldap:
      development:
        cookies:
          secure: false 
          field: 'backstage-token'
        
        ldapAuthenticationOptions:
          userSearchBase: OU=Users,OU=T.O.M.,DC=tompay,DC=local
          usernameAttribute: sAMAccountName

          adminDn: ${ADMIN_DN}
          adminPassword: ${ADMIN_PW}

          ldapOpts:
              url:
                  - ${LDAP_URL}
              tlsOptions:
                  rejectUnauthorized: true
```

And for the Backstage LDAP plugin:

```
ldap:
  providers:
    - target: ${LDAP_URL}
      bind:
        dn: ${ADMIN_DN}
        secret:  ${ADMIN_PW}
      users:
        dn: OU=Users,OU=T.O.M.,DC=tompay,DC=local
        options:
          filter: (&(objectCategory=Person)(|(sAMAccountName=dp*)(sAMAccountName=tp*)))
          scope: sub
        map:
          displayName: sAMAccountName
          email: mail
          name: sAMAccountName
      groups:
        dn: OU=Groups,OU=T.O.M.,DC=tompay,DC=local
        options:
          filter: (&(objectClass=group))
          scope: sub
        map:
          displayName: name
          email: mail
          name: name
```

Thanks for your help.
