### ISSUE TITLE
ldap/refresh responding with 404

### ISSUE THREAD

**Issue by sandepten** [immobiliare/backstage-plugin-ldap-auth#767]
Here is the terminal log:
rootHttpRouter info ::1 - - [05/Aug/2024:09:53:03 +0000] "POST /api/auth/ldap/refresh HTTP/1.1" 404 - "http://localhost:3000/" "Mozilla/5.0 (Macintos

Did exactly as the Guide said regarding the frontend and backend.
What can be the reason?

**Comment by antoniomuso** [comment]
Can you post more info? Like your plugin configuration and so on?

**Comment by sandepten** [comment]
Sure, here is my backend/src/index.ts file:

```
/*
 * Hi!
 *
 * Note that this is an EXAMPLE Backstage backend. Please check the README.
 *
 * Happy hacking!
 */

import { createBackend } from '@backstage/backend-defaults';
import { Config } from '@backstage/config';
import {
  JWTTokenValidator,
  TokenValidator,
  tokenValidatorFactory,
} from '@immobiliarelabs/backstage-plugin-ldap-auth-backend';
import Keyv from 'keyv';

const backend = createBackend();

function createTokenValidator(config: Config): TokenValidator {
  const url = `postgresql://postgres:password@localhost:5432/backstage`;
  return new JWTTokenValidator(new Keyv(url, { table: 'token' }));
}

backend.add(import('@backstage/plugin-app-backend/alpha'));
backend.add(import('@backstage/plugin-proxy-backend/alpha'));
backend.add(import('@backstage/plugin-scaffolder-backend/alpha'));
backend.add(import('@backstage/plugin-techdocs-backend/alpha'));

// auth plugin
backend.add(import('@backstage/plugin-auth-backend'));
// See https://backstage.io/docs/backend-system/building-backends/migrating#the-auth-plugin
backend.add(import('@backstage/plugin-auth-backend-module-guest-provider'));
// See https://backstage.io/docs/auth/guest/provider

// catalog plugin
backend.add(import('@backstage/plugin-catalog-backend/alpha'));
backend.add(
  import('@backstage/plugin-catalog-backend-module-scaffolder-entity-model'),
);

// See https://backstage.io/docs/features/software-catalog/configuration#subscribing-to-catalog-errors
backend.add(import('@backstage/plugin-catalog-backend-module-logs'));

// permission plugin
backend.add(import('@backstage/plugin-permission-backend/alpha'));
backend.add(
  import('@backstage/plugin-permission-backend-module-allow-all-policy'),
);

// search plugin
backend.add(import('@backstage/plugin-search-backend/alpha'));

// search engine
// See https://backstage.io/docs/features/search/search-engines
backend.add(import('@backstage/plugin-search-backend-module-pg/alpha'));

// search collators
backend.add(import('@backstage/plugin-search-backend-module-catalog/alpha'));
backend.add(import('@backstage/plugin-search-backend-module-techdocs/alpha'));

// ldap
backend.add(import('@backstage/plugin-catalog-backend-module-ldap'));
backend.add(import('@immobiliarelabs/backstage-plugin-ldap-auth-backend'));
backend.add(tokenValidatorFactory({ createTokenValidator }));

backend.start();
```

Here is the auth configuration in app config:
```
auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  providers:
    # See https://backstage.io/docs/auth/guest/provider
    ldap:
      development:
        cookies:
          secure: false
          field: 'backstage-token'
        ldapAuthenticationOptions:
          userSearchBase: ${USER_SEARCH_BASE}
          usernameAttribute: 'username'
          ldapOpts:
            url:
              - ${LDAP_URL}
            tlsOptions:
              rejectUnauthorized: false
          adminDn: ${LDAP_ADMIN_DN}
          adminPassword: ${LDAP_ADMIN_PASSWORD}
```

And here is the catalog:
```
catalog:
  providers:
    ldapOrg:
      default:
        target: ${LDAP_URL}
        bind:
          dn: ${DN}
          secret: ${SECRET}
        users:
          dn: ${USER_DN}
        schedule:
          frequency: PT10M
          timeout: PT15M
```

And the frontend App.tsx:
const app = createApp({
  apis,
  bindRoutes({ bind }) {
    bind(catalogPlugin.externalRoutes, {
      createComponent: scaffolderPlugin.routes.root,
      viewTechDoc: techdocsPlugin.routes.docRoot,
      createFromTemplate: scaffolderPlugin.routes.selectedTemplate,
    });
    bind(apiDocsPlugin.externalRoutes, {
      registerApi: catalogImportPlugin.routes.importPage,
    });
    bind(scaffolderPlugin.externalRoutes, {
      registerComponent: catalogImportPlugin.routes.importPage,
      viewTechDoc: techdocsPlugin.routes.docRoot,
    });
    bind(orgPlugin.externalRoutes, {
      catalogIndex: catalogPlugin.routes.catalogIndex,
    });
  },
  components: {
    SignInPage: props => <LdapAuthFrontendPage {...props} provider="ldap" />,
    // SignInPage: props => <SignInPage {...props} auto providers={['guest']} />,
  },
});

**Comment by sandepten** [comment]
Hey @antoniomuso 

Any update regarding this issue? Could you help me

**Comment by antoniomuso** [comment]
Hi @sandepten, I am currently on vacation. When I come back I will help you 😁

**Comment by antoniomuso** [comment]
@sandepten Can you also send me the body of the response, looking at it in the browser?

**Comment by sandepten** [comment]
@antoniomuso Here is the body of the response:

```
{
    "error": {
        "name": "NotFoundError",
        "message": "Unknown auth provider 'ldap'",
        "stack": "NotFoundError: Unknown auth provider 'ldap'\n    at <anonymous> (/Users/sandeep450.kumar/code/projects/backstage-main/node_modules/@backstage/plugin-auth-backend/src/service/router.ts:179:11)\n    at handleReturn (/Users/sandeep450.kumar/code/projects/backstage-main/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at /Users/sandeep450.kumar/code/projects/backstage-main/node_modules/express-promise-router/lib/express-promise-router.js:64:7\n    at Layer.handle [as handle_request] (/Users/sandeep450.kumar/code/projects/backstage-main/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/Users/sandeep450.kumar/code/projects/backstage-main/node_modules/express/lib/router/index.js:328:13)\n    at /Users/sandeep450.kumar/code/projects/backstage-main/node_modules/express/lib/router/index.js:286:9\n    at param (/Users/sandeep450.kumar/code/projects/backstage-main/node_modules/express/lib/router/index.js:365:14)\n    at param (/Users/sandeep450.kumar/code/projects/backstage-main/node_modules/express/lib/router/index.js:376:14)\n    at Function.process_params (/Users/sandeep450.kumar/code/projects/backstage-main/node_modules/express/lib/router/index.js:421:3)\n    at next (/Users/sandeep450.kumar/code/projects/backstage-main/node_modules/express/lib/router/index.js:280:10)\n    at /Users/sandeep450.kumar/code/projects/backstage-main/node_modules/express/lib/router/index.js:646:15\n    at next (/Users/sandeep450.kumar/code/projects/backstage-main/node_modules/express/lib/router/index.js:265:14)\n    at Function.handle (/Users/sandeep450.kumar/code/projects/backstage-main/node_modules/express/lib/router/index.js:175:3)\n    at router (/Users/sandeep450.kumar/code/projects/backstage-main/node_modules/express/lib/router/index.js:47:12)\n    at handleReturn (/Users/sandeep450.kumar/code/projects/backstage-main/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at router (/Users/sandeep450.kumar/code/projects/backstage-main/node_modules/express-promise-router/lib/express-promise-router.js:64:7)"
    },
    "request": {
        "method": "POST",
        "url": "/api/auth/ldap/refresh"
    },
    "response": {
        "statusCode": 404
    }
}
```

**Comment by antoniomuso** [comment]
Ok, your LDAP query is configured wrong. You have to configure well this to match your users: 
```yaml
ldapAuthenticationOptions:
          userSearchBase: ${USER_SEARCH_BASE}
          usernameAttribute: 'username'
          ldapOpts:
            url:
              - ${LDAP_URL}
            tlsOptions:
              rejectUnauthorized: false
          adminDn: ${LDAP_ADMIN_DN}
          adminPassword: ${LDAP_ADMIN_PASSWORD}
```
